version: '3.9'
services:
  website:
    container_name: website
    build: ./docker/website
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./website:/var/www/html
      - ./logs/website:/var/log/apache2 # apache_logs
  api:
    container_name: api
    image: nours313/franken-formations-api:latest
    ports:
      - "8001:443"
      - "8001:443/udp"
volumes:
  logs: